from typing import Optional
from typing_extensions import TypedDict

from models.application import GrantApplication
from models.planner_models import ExecutionPlan
from models.review_models import QualityReview
from models.tool_models import ToolResult


class GrantState(TypedDict):
    # Original grant application
    application: GrantApplication

    # Planner output
    plan: Optional[ExecutionPlan]

    # Tool outputs
    tool_results: dict[str, ToolResult]

    # Optional summary generated by Worker
    worker_result: dict

    # Quality Reviewer output
    review: Optional[QualityReview]

    # Final Judge decision (to be added later)
    final_decision: Optional[str]

# Why not use a Python class?

# Because LangGraph expects a serializable state.

# A TypedDict gives us:

# lightweight state
# type hints
# compatibility with LangGraph
# easy debugging

# Later, we may switch to a Pydantic state if we want stricter validation, but TypedDict is the standard starting point.